### ISSUE TITLE
Issues with Kotlin Dependencies

### ISSUE THREAD

**Issue by btmonier** [AlexanderPrendota/kotlin-compiler-server#193]
Hello,

I am not sure if this is a Gradle specific question but I have been having some issues setting up my own compiler server with the Kotlin library, [Krangl](https://github.com/holgerbrandl/krangl). I try adding in the library as:

`kotlinDependency("de.mpicbg.scicomp:krangl:0.13")`

in the dependencies section and adding `jcenter()` in the repositories section of the build file. However when I build this, I get the following error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/klaxon/JsonArray
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
        at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3192)
        at java.base/java.lang.Class.getMethods(Class.java:1905)
        at indexation.MainKt.allFunctionsFromClass(Main.kt:105)
        at indexation.MainKt.getVariantsForZip(Main.kt:100)
        at indexation.MainKt.getAllVariants(Main.kt:162)
        at indexation.MainKt.createJsonWithIndexes(Main.kt:168)
        at indexation.MainKt.main(Main.kt:22)
Caused by: java.lang.ClassNotFoundException: com.beust.klaxon.JsonArray
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:864)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 9 more
```

Looking at the dependencies for Krangl, I notice that it requires two additional compile dependencies that are not found in the build file:

* `com.beust:klaxon:0.30`
* `org.apache.commons:commons-csv:1.3`

Adding these to the build file (as `kotlinDependency()`) allows for a successful build and I am able to deploy the server and run code snippets with no problems. My question is _can I just add the Krangl library and automatically pull in all dependencies?_ I feel like this could become bothersome if trying to add more libraries to the server. Thanks!

**Comment by AlexanderPrendota** [comment]
Hey, thanks for the issue. Yes, because kotlinDependency configuration has isTransitive property with a false value.

```kotlin
val kotlinDependency: Configuration by configurations.creating {
    isTransitive = false
}
```

**Comment by AlexanderPrendota** [comment]
AFAIR kotlin std-libs produce some transitive dependencies that we don't need in classpath. But I understand your pain and should have a look at this issue from another side. Thanks!

**Comment by btmonier** [comment]
Ahh, I understand now. To get around this, I essentially made my own `kotlinDependency()` configuration with the transitive property set to `true` and that worked. Thanks again!

**Comment by btmonier** [comment]
Hello again,

I have encountered another error when trying to remedy this transitive property. I have made a separate configuration value with the transitive property set to `true`:

```kotlin
val myDependency: Configuration by configurations.creating {
    isTransitive = true
}
```

And have also added this dependency to (1) a new `copyDependency`:

```kotlin
val copyMyDependencies by tasks.creating(Copy::class) {
    from(myDependency)
    into(libJVMFolder)
}
```

and to (2) `tasks`:

```kotlin
tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict", "-Xskip-metadata-version-check")
        jvmTarget = "1.8"
    }
    dependsOn(copyDependencies)
    dependsOn(copyMyDependencies)
    dependsOn(copyJSDependencies)
    dependsOn(":executors:jar")
    dependsOn(":indexation:run")
    buildPropertyFile()
}
```

However, when I re-run the build script with the following addition to the dependency section...
```kotlin
myDependency("de.mpicbg.scicomp:krangl:0.13")
```
...I am able to obtain the jar files, but I get this following error:

```
Exception in thread "main" java.lang.NullPointerException: canonicalName must not be null
        at indexation.MainKt.allClassesFromJavaClass(Main.kt:41)
        at indexation.MainKt.getVariantsForZip(Main.kt:98)
        at indexation.MainKt.getAllVariants(Main.kt:162)
        at indexation.MainKt.createJsonWithIndexes(Main.kt:168)
        at indexation.MainKt.main(Main.kt:22)
```

Any ideas? Thanks again!

**Comment by AlexanderPrendota** [comment]
@PolinB could you help us here? There is a problem with building an index for auto-completion & auto-imports

**Comment by AlexanderPrendota** [comment]
We should add a [filter for the null](https://github.com/AlexanderPrendota/kotlin-compiler-server/blob/16e4be38aec0d20012d92de16531ae794c80a391/indexation/src/main/kotlin/Main.kt#L41) values or set the nullable type to the property importName from ImportInfo class.
