### ISSUE TITLE
bootJar not working

### ISSUE THREAD

**Issue by Surya-Pushpa** [AlexanderPrendota/kotlin-compiler-server#270]
./gradlew bootJar generates jar file under ./libs/ but throws java.lang.IllegalStateException and other exceptions on execution.

**Comment by AlexanderPrendota** [comment]
Hey, thanks for the issue.

```
./gradlew bootJar
BUILD SUCCESSFUL in 47s
```

for my side. Could you please add more descriptions, logs, and something else to reproduce your problem?

**Comment by Surya-Pushpa** [comment]
Sure, as a next step, on execution of jar using 
```

>> java -jar ./build/libs/kotlin-compiler-server-1.4.30-SNAPSHOT.jar 

[           main] o.s.boot.SpringApplication               : Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'kotlinProjectExecutor' defined in URL [jar:file:/kotlin-compiler-server/build/libs/kotlin-compiler-server-1.4.30-SNAPSHOT.jar!/BOOT-INF/classes!/com/compiler/server/service/KotlinProjectExecutor.class]: 
Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'kotlinCompiler' defined in URL [jar:file:/kotlin-compiler-server/build/libs/kotlin-compiler-server-1.4.30-SNAPSHOT.jar!/BOOT-INF/classes!/com/compiler/server/compiler/components/KotlinCompiler.class]: 
Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'errorAnalyzer' defined in URL [jar:file:/kotlin-compiler-server/build/libs/kotlin-compiler-server-1.4.30-SNAPSHOT.jar!/BOOT-INF/classes!/com/compiler/server/compiler/components/ErrorAnalyzer.class]: 
Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'kotlinEnvironment' defined in class path resource [com/compiler/server/compiler/components/KotlinEnvironmentConfiguration.class]: 
Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: 
Failed to instantiate [component.KotlinEnvironment]: 
Factory method 'kotlinEnvironment' threw exception; nested exception is java.lang.IllegalStateException: Unable to find extension point configuration extensions/compiler.xml (cp:
null)
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.5.jar!/:5.3.5]
at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.5.jar!/:5.3.5]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354) ~[spring-beans-5.3.5.jar!/:5.3.5]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.3.5.jar!/:5.3.5]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.5.jar!/:5.3.5]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.5.jar!/:5.3.5]
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.5.jar!/:5.3.5]
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.5.jar!/:5.3.5]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.5.jar!/:5.3.5]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.5.jar!/:5.3.5]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.5.jar!/:5.3.5]
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.5.jar!/:5.3.5]
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.5.jar!/:5.3.5]
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.4.jar!/:2.4.4]
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:769) [spring-boot-2.4.4.jar!/:2.4.4]
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) [spring-boot-2.4.4.jar!/:2.4.4]
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) [spring-boot-2.4.4.jar!/:2.4.4]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [spring-boot-2.4.4.jar!/:2.4.4]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1313) [spring-boot-2.4.4.jar!/:2.4.4]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) [spring-boot-2.4.4.jar!/:2.4.4]
at com.compiler.server.CompilerApplicationKt.main(CompilerApplication.kt:13) [classes!/:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_282]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_282]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_282]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_282]
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [kotlin-compiler-server-1.4.30-SNAPSHOT.jar:na]
at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [kotlin-compiler-server-1.4.30-SNAPSHOT.jar:na]
at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [kotlin-compiler-server-1.4.30-SNAPSHOT.jar:na]
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [kotlin-compiler-server-1.4.30-SNAPSHOT.jar:na]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'kotlinCompiler' defined in URL

```

**Comment by AlexanderPrendota** [comment]
Oh, got it.

A long time ago I removed a correct `bootJar` configuration because I found [another way](https://github.com/AlexanderPrendota/kotlin-compiler-server/blob/492f081d8144af5e033694f565f555d2a6f3841d/Dockerfile#L28) to start the application from the docker container.

Please add the snippet to your build.gradle.kts

```kotlin

tasks.withType<org.springframework.boot.gradle.tasks.bundling.BootJar> {
    //https://stackoverflow.com/questions/57727150/kotlin-script-engine-with-spring-boot-self-running-war
    requiresUnpack("**/kotlin-*.jar")
    requiresUnpack("**/kotlinx-*.jar")
}

```

I have just copied from git history

**Comment by Surya-Pushpa** [comment]
Hey, its working.. thanks
The only dependency are 
- kotlin libs jar under dir ${kotlin_version} &
- executor.policy

**Comment by AlexanderPrendota** [comment]
yes, just put files near the jar =)
