### ISSUE TITLE
access denied - PropertyPermission error

### ISSUE THREAD

**Issue by christian-draeger** [AlexanderPrendota/kotlin-compiler-server#286]
I'm experimenting with kotlin-compiler-server in combination with kotlin playground since i am planing to use it as part of my documentation for a library i am maintaining.

i forked the kotlin-compiler-server to be able to add the library i want to use (including it transitive dependencies) in my  documentaton.

whenever i try to run the example i am getting following error:

> Exception in thread "main" java.security.AccessControlException: Access control exception due to security reasons in web playground: 
 access denied ("java.util.PropertyPermission" "io.ktor.development" "read")
 at java.lang.SecurityManager.checkPermission (SecurityManager.java:408) 
 
since my library has several transitive dependencies, e.g. the ktor http client and the exception is complaining about something with ktor, i added my dependency with `isTransitive = true` as well as adding all ktor jars that comes transitively to the `executor.policy` - here is what i tried: https://github.com/skrape-it/kotlin-compiler-server/commit/069c77dc0bb8ca023477a55593e37665e17b39d0 

here what it looks like in the ui:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22223458/117716942-75aa1600-b1da-11eb-9aca-f673f8666617.gif)

what am i doing wrong?

**Comment by AlexanderPrendota** [comment]
Hey, you need to configure the java security policy.
My default version is [here](https://github.com/AlexanderPrendota/kotlin-compiler-server/blob/master/executor.policy).

And also I run the application via `java -cp` and add the [-Djava.security.policy=$policy](https://github.com/AlexanderPrendota/kotlin-compiler-server/blob/f5c384f9b5a3a2e968950623d1ef8c5579d8e44b/src/main/kotlin/com/compiler/server/executor/JavaExecutor.kt#L116) flag. You can just remove it but it is not secure.

**Comment by AlexanderPrendota** [comment]
but also u need to add the permission for `java.util.PropertyPermission" "io.ktor.development" "read"`

**Comment by christian-draeger** [comment]
here is what i tried: https://github.com/skrape-it/kotlin-compiler-server/commit/e168601fdca5728b2d9524da5e69c877cbe1b0dd

getting another error now:

![image](https://user-images.githubusercontent.com/22223458/118409964-60773080-b68d-11eb-8811-fa6650bd4cea.png)

is the permission set correctly?

also not quite sure what you mean by 
> And also I run the application via java -cp and add the -Djava.security.policy=$policy flag. You can just remove it but it is not secure.

i just start the spring-boot service from intellijs run config

when trying to to create a fatjar via `./gradlew bootJar` and start it from terminal via `java -jar build/libs/kotlin-compiler-server-1.5.0-SNAPSHOT.jar -Djava.security.policy=$policy`

i am getting the following stacktrace which i don't now what it tries to tell me tbh ^^
(same behaviour when trying to run the jar without the policy parameter)

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'kotlinProjectExecutor' defined in URL [jar:file:/Users/christiandrager/github/kotlin-compiler-server/build/libs/kotlin-compiler-server-1.5.0-SNAPSHOT.jar!/BOOT-INF/classes!/com/compiler/server/service/KotlinProjectExecutor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'kotlinCompiler' defined in URL [jar:file:/Users/christiandrager/github/kotlin-compiler-server/build/libs/kotlin-compiler-server-1.5.0-SNAPSHOT.jar!/BOOT-INF/classes!/com/compiler/server/compiler/components/KotlinCompiler.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'errorAnalyzer' defined in URL [jar:file:/Users/christiandrager/github/kotlin-compiler-server/build/libs/kotlin-compiler-server-1.5.0-SNAPSHOT.jar!/BOOT-INF/classes!/com/compiler/server/compiler/components/ErrorAnalyzer.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kotlinEnvironment' defined in class path resource [com/compiler/server/compiler/components/KotlinEnvironmentConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [component.KotlinEnvironment]: Factory method 'kotlinEnvironment' threw exception; nested exception is java.lang.IllegalStateException: Unable to find extension point configuration extensions/compiler.xml (cp:
  null)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.6.jar!/:5.3.6]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.6.jar!/:5.3.6]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:782) ~[spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:774) ~[spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) ~[spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) ~[spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) ~[spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) ~[spring-boot-2.4.5.jar!/:2.4.5]
        at com.compiler.server.CompilerApplicationKt.main(CompilerApplication.kt:13) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[kotlin-compiler-server-1.5.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[kotlin-compiler-server-1.5.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[kotlin-compiler-server-1.5.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[kotlin-compiler-server-1.5.0-SNAPSHOT.jar:na]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'kotlinCompiler' defined in URL [jar:file:/Users/christiandrager/github/kotlin-compiler-server/build/libs/kotlin-compiler-server-1.5.0-SNAPSHOT.jar!/BOOT-INF/classes!/com/compiler/server/compiler/components/KotlinCompiler.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'errorAnalyzer' defined in URL [jar:file:/Users/christiandrager/github/kotlin-compiler-server/build/libs/kotlin-compiler-server-1.5.0-SNAPSHOT.jar!/BOOT-INF/classes!/com/compiler/server/compiler/components/ErrorAnalyzer.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kotlinEnvironment' defined in class path resource [com/compiler/server/compiler/components/KotlinEnvironmentConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [component.KotlinEnvironment]: Factory method 'kotlinEnvironment' threw exception; nested exception is java.lang.IllegalStateException: Unable to find extension point configuration extensions/compiler.xml (cp:
  null)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.6.jar!/:5.3.6]
        ... 28 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'errorAnalyzer' defined in URL [jar:file:/Users/christiandrager/github/kotlin-compiler-server/build/libs/kotlin-compiler-server-1.5.0-SNAPSHOT.jar!/BOOT-INF/classes!/com/compiler/server/compiler/components/ErrorAnalyzer.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kotlinEnvironment' defined in class path resource [com/compiler/server/compiler/components/KotlinEnvironmentConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [component.KotlinEnvironment]: Factory method 'kotlinEnvironment' threw exception; nested exception is java.lang.IllegalStateException: Unable to find extension point configuration extensions/compiler.xml (cp:
  null)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.6.jar!/:5.3.6]
        ... 42 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kotlinEnvironment' defined in class path resource [com/compiler/server/compiler/components/KotlinEnvironmentConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [component.KotlinEnvironment]: Factory method 'kotlinEnvironment' threw exception; nested exception is java.lang.IllegalStateException: Unable to find extension point configuration extensions/compiler.xml (cp:
  null)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.6.jar!/:5.3.6]
        ... 56 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [component.KotlinEnvironment]: Factory method 'kotlinEnvironment' threw exception; nested exception is java.lang.IllegalStateException: Unable to find extension point configuration extensions/compiler.xml (cp:
  null)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.6.jar!/:5.3.6]
        ... 70 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to find extension point configuration extensions/compiler.xml (cp:
  null)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerApplicationExtensionPointsAndExtensionsFrom(KotlinCoreEnvironment.kt:563) ~[kotlin-compiler-1.5.0.jar!/:1.5.0-release-749 (1.5.0)]
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createApplicationEnvironment(KotlinCoreEnvironment.kt:534) ~[kotlin-compiler-1.5.0.jar!/:1.5.0-release-749 (1.5.0)]
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.getOrCreateApplicationEnvironment(KotlinCoreEnvironment.kt:491) ~[kotlin-compiler-1.5.0.jar!/:1.5.0-release-749 (1.5.0)]
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.getOrCreateApplicationEnvironmentForProduction(KotlinCoreEnvironment.kt:479) ~[kotlin-compiler-1.5.0.jar!/:1.5.0-release-749 (1.5.0)]
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:423) ~[kotlin-compiler-1.5.0.jar!/:1.5.0-release-749 (1.5.0)]
        at component.KotlinEnvironment.<init>(KotlinEnvironment.kt:105) ~[common.jar!/:na]
        at com.compiler.server.compiler.components.KotlinEnvironmentConfiguration.kotlinEnvironment(KotlinEnvironment.kt:38) ~[classes!/:na]
        at com.compiler.server.compiler.components.KotlinEnvironmentConfiguration$$EnhancerBySpringCGLIB$$767af723.CGLIB$kotlinEnvironment$0(<generated>) ~[classes!/:na]
        at com.compiler.server.compiler.components.KotlinEnvironmentConfiguration$$EnhancerBySpringCGLIB$$767af723$$FastClassBySpringCGLIB$$ad21387e.invoke(<generated>) ~[classes!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.6.jar!/:5.3.6]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.6.jar!/:5.3.6]
        at com.compiler.server.compiler.components.KotlinEnvironmentConfiguration$$EnhancerBySpringCGLIB$$767af723.kotlinEnvironment(<generated>) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.6.jar!/:5.3.6]
        ... 71 common frames omitted

```

**Comment by AlexanderPrendota** [comment]
Hey, does it work if u disable the security policy?

For the second part of the question:
https://github.com/AlexanderPrendota/kotlin-compiler-server/issues/270
